### ISSUE TITLE
Konvertere Årsmøte til å være en type Arrangement

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#101]
En fordel blir å kunne utvikle invitasjoner, meldinger og filer for alle Arrangement.

**Comment by donv** [comment]
Utført.  @saxofonia @AtleTollefsen @Atle-Tollefsen

**Comment by Atle-Tollefsen** [comment]
Topp


Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

Fra: Uwe Kubosch<mailto:notifications@github.com>
Sendt: onsdag 8. april 2020 kl. 08:22
Til: Romerike-Jujutsu-Klubb/rjjk_web<mailto:rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen<mailto:Atle@gjemmekontor.no>; Mention<mailto:mention@noreply.github.com>
Emne: Re: [Romerike-Jujutsu-Klubb/rjjk_web] Konvertere Årsmøte til å være en type Arrangement (#101)


Closed #101<https://github.com/Romerike-Jujutsu-Klubb/rjjk_web/issues/101>.
