### ISSUE TITLE
Legge ut nyheter fras forbundet

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#103]
Fra @saxofonia :
    Vedlegger nyhetsbrev juni fra forbundet.
    Uwe: Finnes det, eller kan det lages, noen måte å legge disse ut på webben så vi kan nå medlemmene våre på en så enkel som mulig måte?

**Comment by saxofonia** [comment]
Ikke godt å si. Dette er mailer, så det finnes ikke nyhetsbrev på web. Men,
er det viktig, da? Vi legger jo ut det som kan være av interesse på vår
web, og folk kan lese selv...

Dersom du har tid, så...   :-)


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: post@jujutsu.no
Web: http://www.jujutsu.no



fre. 10. apr. 2020 kl. 19:25 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Ikke viktig for meg.
