### ISSUE TITLE
Fjerne varsler om deltagelse på treninger som er avlyst (ferie, o.l.)

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#123]
Hadde det vært mulig å stoppe melding om deltagelse, både for instruktør og utøver, på treninger som er avlyst? F.eks. i ferieperioden, o.l.

**Comment by donv** [comment]
Har lagt inn at oppmøtemeldinger for grupper som følger skoleåret stoppes i feriene.
