### ISSUE TITLE
Lage oppmøtelista rask

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#150]

**Comment by Vegandi** [comment]
Altså snøggere enn 4 sek.

**Comment by donv** [comment]
Jeg tenker vi er innafor nå.

**Comment by Vegandi** [comment]
Helt klart!

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


fre. 4. des. 2020 kl. 10:08 skrev Uwe Kubosch <notifications@github.com>:
