### ISSUE TITLE
Er det mulig å registrere bindingstid på medlemmer?

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#154]
Altså at de har mottatt gratis drakt og dato for utlevering.

**Comment by saxofonia** [comment]
Det kan være fint at nye medlemmer kan registrere at de ønsker å motta en gratis drakt mot 6 mnd. bindingstid når de registrerer seg?

**Comment by donv** [comment]
Starter på denne nå.

**Comment by donv** [comment]
@saxofonia Da har jeg lagt til registrering av bindingstid med en knapp for å sette bindingstid 6 måneder frem i tid.

Feltet er på "Medlemskap" arkfanen.

Ser det greit ut?

**Comment by saxofonia** [comment]
Hei!

Ser bra ut. Går det an å liste det feltet på Drilldown, eller noe, også ved
behov?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



man. 4. jan. 2021 kl. 01:02 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Da er feltet lagt til i drilldown også.

**Comment by saxofonia** [comment]
Toppers!  :-)



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



ons. 6. jan. 2021 kl. 17:11 skrev Uwe Kubosch <notifications@github.com>:
