### ISSUE TITLE
Innmelding

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#155]
Hvorfor må foreldre registrere fødselsdato når de registrerer seg som foresatt?

![image](https://user-images.githubusercontent.com/28863697/99984905-edf85880-2dad-11eb-80a9-9bb59ca3784e.png)

**Comment by saxofonia** [comment]
Får ikke lov å registrere!
![image](https://user-images.githubusercontent.com/28863697/99985563-65c68300-2dae-11eb-96f6-973a9956b1d3.png)

**Comment by donv** [comment]
Nei, det trengs vel ikke..  Fikser…

**Comment by donv** [comment]
Da har jeg fjernet feltene for kjønn og fødselsdato for foresatt.

**Comment by donv** [comment]
Du prøvde å registrere med e-post "cagman_no@yahoo.no" som finnes fra før.

Hvem er det du vil registrere?

**Comment by saxofonia** [comment]
Dattera. Husker ikke navnet her. Jeg har registrert henne bakveien (NKF),
men for fremtiden...

Greit om det står noe om at man ikke kan registrere samme mailadresse to
ggr på samme registrering. Det er ikke selvklart...


SRR


man. 23. nov. 2020, 19:19 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Skjønner.  Har du noe forslag til hvordan det kan formidles bedre?

I første omgang tar jeg og sjekker at e-post for medlem og foresatt ikke er den samme i hvert fall.

**Comment by donv** [comment]
Denne er vel i orden nå.
