### ISSUE TITLE
Får ikke meldt meg på tilsendt arrangement

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#156]
![image](https://user-images.githubusercontent.com/28863697/99990092-b2608d00-2db3-11eb-9b91-5dd3103546da.png)

**Comment by donv** [comment]
@saxofonia Ser ut som du er påmeldt nå?

**Comment by saxofonia** [comment]
Hvis det er Planlegging av våren 2021, så...


Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



tir. 8. des. 2020 kl. 20:48 skrev Uwe Kubosch <notifications@github.com>:
