### ISSUE TITLE
Hvorfor er Marita Grønseth registrert som medlem når hun bare er en forelder?

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#157]
<img width="317" alt="Skjermbilde 2020-11-23 kl  21 04 15" src="https://user-images.githubusercontent.com/28863697/100010563-bbac2280-2dd0-11eb-840e-454004302a4a.png">
<img width="1113" alt="Skjermbilde 2020-11-23 kl  21 04 34" src="https://user-images.githubusercontent.com/28863697/100010567-bc44b900-2dd0-11eb-8688-98d396ba2161.png">

Hun er moren til Stella Marita Langen

**Comment by donv** [comment]
I den opprinnelige importen fra NKF var det kreativ bruk at e-postadresser slik at Stella ble registrert med Marita sin e-post og fikk to oppmøter registrert på seg.

Etter at jeg ryddet opp i registreringen ble oppmøtene liggende igjen på Marita.

Jeg har lagt til funksjon for å slette oppmøter på folk som ikke har noe medlemskap og slettet oppmøtene fro Marita.  Da er hun borte fra oppmøtelistene.

Vær også oppmerksom på at alle folk kan nå legges til på en gruppe og få oppmøte selv om de ikke er medlemmer.  Dette for å lette registrering for prøvemedlemmer.
