### ISSUE TITLE
Det er 2 Ola Tobias her, men det er bare ett medlem!

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#158]
<img width="285" alt="Skjermbilde 2020-11-23 kl  21 06 06" src="https://user-images.githubusercontent.com/28863697/100010686-ebf3c100-2dd0-11eb-8a24-0add14835d18.png">

**Comment by donv** [comment]
Hvor er dette?

**Comment by donv** [comment]
Fant det!

**Comment by donv** [comment]
Fikset!
