### ISSUE TITLE
Godkjente medlemmer fra NKF blir ikke synkronisert på webben

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#159]
Ludvig er plutselig borte fra webben.
Julia og Hanna blir ikke merket som medlemmer.
Alle disse er godkjente i NKF.
![image](https://user-images.githubusercontent.com/28863697/100427029-1d4ee400-3092-11eb-8762-0fba697fb4e7.png)

**Comment by donv** [comment]
Har lagt opp en fiks for dette nå.
