### ISSUE TITLE
Integrasjon med IMS (NIF)

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#160]
https://www.idrettsforbundet.no/digital/samarbeidspartner/api-medlem/

**Comment by donv** [comment]
Det ser ut som vi ikke får API-tilgang.  Det betyr at eventuell integrasjon må gjøres via web-grensesnittet.  Dette er bak en sikker innlogging, så det kan bli mye jobb (umulig?) å integrere.  Vi får se på det når det er skikkelig tilgjengelig.

For manuell synkronisering før vi har en eventuell integrasjon, kan vi bruke innmeldinglisten og merke av de som er innmeldt til NIF.

**Comment by donv** [comment]
@saxofonia kan du (eller noen andre) sende meg et eksempel på export-fil for medlemmer fra IMS?

**Comment by saxofonia** [comment]
Hei!

Legger ved to versjoner. Begge er .csv. Den ene er fra Beta og den andre
(mindre) er Produksjon.

Sender med Excel også.



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



ons. 28. jul. 2021 kl. 11:20 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Utgår.
