### ISSUE TITLE
Hvordan sendes avtalegirokontrakt (eller annen form for fremtidig kontrakt) til prøvemedlemmer?

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#161]

**Comment by donv** [comment]
Slik det ser ut nå må det nye medlemsregisteret føres manuelt og ta seg av alt med betaling.

**Comment by saxofonia** [comment]
Jeg har ikke fått adminrettigheter i IMS enda, men det er synd om vi ikke
finner en automatisk kopieringsløsning, som i dag, med det kan sikkert
lages en WA med manuell eksportering og importering?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



man. 28. des. 2020 kl. 10:30 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Det skal vi nok få til.
