### ISSUE TITLE
Timeout på https://jujutsu.no/oppm%C3%B8te/skjema/2020/10/2

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#162]
https://jujutsu.no/oppm%C3%B8te/skjema/2020/10/2

**Comment by donv** [comment]
@vegandi Da svarer den på 4-5 sekunder.

**Comment by donv** [comment]
@Vegandi Ble det bra?

**Comment by Vegandi** [comment]
> @Vegandi Ble det bra?

Jepp, har nettopp sjekka. :-) Bra jobba! 

Og ja, det ser ut som om jeg får varsel fra saker jeg ikke har registrert sjøl. Det er bare det at det kan ta litt tid før jeg svarer, for jeg legger meg klokka 22, og da har jo du andre arbeidsøkt for dagen...
