### ISSUE TITLE
Rabatt på medlemssida: tydeligere for leser? 

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#163]
Rullegardinvariant som vises under feltet for rabatt, med hake for valgt rabatt? Sånn det er nå står det for eksempel på meg "0" i feltet for rabatt, men ved sida av står det "Halv instruktør". Det er tvetydig. Ideelt sett burde det vært haka av hvilken rabatt som er gjeldende, og hvilken rabatt man egentlig har krav på, i de tilfellene der det er ulikt. Kan det gjøres så enkelt som 

Ingen rabatt
Instruktør 100*
Instruktør 50 
Styreleder 100 
Styremedlem 100
Materialforvalter 100*
Familierabatt 10 (?)*

Asterisken viser hvilken som er tilrådd, slik som under graderingssidene? Altså: på meg bør det da stå haka av for Ingen rabatt, men asterisk på Materialforvalter 100? 

Har ikke oversikt over hvor mange ulike typer rabatt det er, så jeg har improvisert, beklager om det er rotete.

**Comment by donv** [comment]
Tenker du rullgardin i tillegg til å kunne skrive et tall, eller i stedet for å kunne skrive tall?

Hvis man ikke kan skrive kan vi ikke håndtere spesielle avtaler.  Vi kan legge til noen vanlige valg for rabatt (20%, 25%, 33%, etc) i tillegg til rabattene som kommer fra verv?

**Comment by Vegandi** [comment]
Hm, litt usikker på om jeg skjønner spørsmålet, men det bør vel være i tillegg, trur jeg, nettopp for å kunne håndtere særavtaler. Godt poeng, det hadde jeg ikke tenkt på. 

Viss det er skikkelig krøkkete å få til å kunne skrive inn også, så er forslaget ditt en god løsning, å legge til standardtall, for det er vel tross alt ikke SÅ sannsynlig at noen kommer til å få 17,2% rabatt heller, da får de heller få 20%.

**Comment by donv** [comment]
@saxofonia Noen innspill?  Du bruker det vel mest.

**Comment by donv** [comment]
### Nytt forslag:

Medlem uten rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 10 00 39" src="https://user-images.githubusercontent.com/57275/101143736-99f43c00-3617-11eb-865d-963dfc52445d.png">

Medlem med beregnet rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 10 02 09" src="https://user-images.githubusercontent.com/57275/101143878-d2941580-3617-11eb-9f13-437a60d55f9c.png">

Medlem med overstyrt rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 09 58 52" src="https://user-images.githubusercontent.com/57275/101143593-66b1ad00-3617-11eb-9ba4-f6fba4ea585e.png">

**Comment by saxofonia** [comment]
Hei!

Tenker du å lage en ekstra felt til overstyring? Er det nødvendig fordi
eksisterende felt ikke kan skrives i dersom det er en beregnet verdi der?


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: post@jujutsu.no
Web: http://www.jujutsu.no



fre. 4. des. 2020 kl. 10:04 skrev Uwe Kubosch <notifications@github.com>:

**Comment by Vegandi** [comment]
Nå har jeg testa forslaget på en tilfeldig medarbeider i hjemmekontorlandskapet, og han rapporterer at det fortsatt er utydelig. Når jeg leser forslaget ditt, MED forklaring, så er det klart som dagen, men når det bare står aleine trur jeg ikke det er like greit å skjønne. Men nå oppdaga jeg at Jokke ikke kan se like mye på si side som det jeg kan, og at dette dermed er mest relevant for admin, og da holder det vel at vi skjønner det. Og så bør du kanskje ikke legge altfor mye arbeid i at jeg skal fatte det, for jeg klikker jo på alt jeg ikke har noe med uansett...

**Comment by donv** [comment]
OK, tenker jeg stopper her:

Medlem uten rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 11 10 07" src="https://user-images.githubusercontent.com/57275/101151187-95348580-3621-11eb-9746-dfb1a1e2ad3d.png">

Medlem med rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 11 10 30" src="https://user-images.githubusercontent.com/57275/101151188-95cd1c00-3621-11eb-8e21-a1f8d2349b20.png">

Styremedlem med beregnet rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 11 10 58" src="https://user-images.githubusercontent.com/57275/101151183-936ac200-3621-11eb-9f12-d5a9407c6190.png">

Styremedlem med overstyrt rabatt:

<img width="633" alt="Screenshot 2020-12-04 at 11 11 16" src="https://user-images.githubusercontent.com/57275/101151186-949bef00-3621-11eb-8e9f-edb303b995aa.png">

**Comment by Vegandi** [comment]
Den er fin!
