### ISSUE TITLE
Treig nettside

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#166]
I dag mandag er nettsida fryktelig treig igjen. :-( Timer ut og får feilmelding, se skjermdump. 
![2021-01-25](https://user-images.githubusercontent.com/73274461/105691704-e106fb00-5efd-11eb-80c0-7beb0016652e.png)

**Comment by donv** [comment]
Ser på det med en gang--Uwe KuboschRomerike Jujutsu Klubbwww.jujutsu.noOn Jan 25, 2021 11:10, Ellen Skjold Kvåle <notifications@github.com> wrote:

I dag mandag er nettsida fryktelig treig igjen. :-( Timer ut og får feilmelding, se skjermdump.

**Comment by Vegandi** [comment]
Jeg sjekka et par andre sider også: pensum, og eget oppmøte. Der går det utrulig treigt, men sida åpner seg. Graderinger, derimot, den sida bare vil ikke. 

(Skulle sjølsagt sjekke om Jokke si gradering var satt opp... :-)

**Comment by donv** [comment]
Har ikke sett på årsak, men dette er andre gang det går tregt.  Har gjort en omstart, så burde være bra igjen.--Uwe KuboschRomerike Jujutsu Klubbwww.jujutsu.noOn Jan 25, 2021 11:15, uwe@kubosch.no wrote:Ser på det med en gang--Uwe KuboschRomerike Jujutsu Klubbwww.jujutsu.noOn Jan 25, 2021 11:10, Ellen Skjold Kvåle <notifications@github.com> wrote:

I dag mandag er nettsida fryktelig treig igjen. :-( Timer ut og får feilmelding, se skjermdump.

**Comment by Vegandi** [comment]
Funker bra nå!
