### ISSUE TITLE
Link til IMS under knappen "Prøv oss"

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#167]
Nye medlemmer må registrere seg direkte på IMS. Hvis ikke har de ikke forsikring. Linken https://medlemskap.nif.no/ bør/må legges under "Prøv oss"-knappen. 

Vi må finne noen gode rutiner til å følge opp videreregistrering, og oppfølging av disse som prøvemedlemmer, da IMS dessverre ikke varsler når nye medlemmer har registrert seg.

Kan du fikse linken i første omgang?

**Comment by saxofonia** [comment]
Bruk denne linken: https://medlemskap.nif.no/Start/Index/20493

**Comment by donv** [comment]
Denne er i orden nå.
