### ISSUE TITLE
Kontaktliste bør knyttes til "Kontakt oss"-lista

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#169]
Hei!

Det er mange plasser å rette opp styresammensetning og instruktøroversikt, så det blir stadig en plass som blir uteglemt, og blir feil. Noen plasser blir listene generert automatisk. Det skulle jeg gjerne sett ble gjort her også.

[[RJJK] Til info_ Kontakt oss.pdf](https://github.com/Romerike-Jujutsu-Klubb/rjjk_web/files/6001160/RJJK.Til.info_.Kontakt.oss.pdf)

SRR

**Comment by donv** [comment]
Starter å se på denne, men er ikke helt sikker på hva løsningen blir.

**Comment by donv** [comment]
Jeg tenker vi kan legge inn koder for de forskjellige vervene.

Her er et forslag:  https://www.jujutsu.no/info/Kontakt%20oss

Hva synes du?

**Comment by saxofonia** [comment]
Hei!

Dette ser bra ut, men det er vel en liten feil her?
[image: image.png]



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



tor. 20. mai 2021 kl. 08:18 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Jeg kan ikke se bildet det er referert til.

Synes du det generelle opplegget med koder er greit?

**Comment by saxofonia** [comment]
Koder?

Bildet viste at telefonnummeret bak navnet mitt ble... navnet mitt. De
andre fikk telefonnummer.


SRR



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



tor. 20. mai 2021 kl. 21:14 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
https://www.jujutsu.no/info/6/edit
