### ISSUE TITLE
Gjøre RJJK til "master" for medlemsinfo

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#17]
@saxofonia :

Da har jeg satt RJJK til å være master for medlemsdata.

**Comment by donv** [comment]
@saxofonia Kan du prøve litt og se at det er OK?  Synkronisering skjer fremdeles hver time.

**Comment by saxofonia** [comment]
Hva er gjort, og hva skal prøves?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766


2017-06-17 13:35 GMT+02:00 Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Alle feltene for et medlem skal nå kunne (og måtte) vedlikeholdes i vår web.  De speiles da over til NKF en gang i timen.

Unntak er nye medlemmer som importeres fra NKF til oss.

--
Uwe Kubosch
uwe@kubosch.no

**Comment by saxofonia** [comment]
Hei!

La inn utmeldt-dato på to medlemmer. Ventet noen timer, men måtte legge inn
datoen i NKF Webben manuelt. Funket ikke.




Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766


2017-06-21 9:51 GMT+02:00 Uwe Kubosch <notifications@github.com>:

> Alle feltene for et medlem skal nå kunne (og måtte) vedlikeholdes i vår
> web. De speiles da over til NKF en gang i timen.
>
> Unntak er nye medlemmer som importeres fra NKF til oss.
>
> --
> Uwe Kubosch
> uwe@kubosch.no
>
>
>

**Comment by donv** [comment]
Flott testing!  Skal se på det.


--
Uwe Kubosch
uwe@kubosch.no

**Comment by donv** [comment]
Hei!

Da har jeg fikset litt.  Klar for ny testing.


--
Uwe Kubosch
uwe@kubosch.no

**Comment by saxofonia** [comment]
Hei!

Jeg kan nå bekrefte at endring sluttedato, satt i medlemswebben, overføres
suksessfult til NKF-portalen.  :-)





Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766


5. august 2017 kl. 12:02 skrev Uwe Kubosch <notifications@github.com>:

> Hei!
>
> Da har jeg fikset litt. Klar for ny testing.
>
>
> --
> Uwe Kubosch
> uwe@kubosch.no
>
>
>

**Comment by donv** [comment]
Woohoo!

Jeg har nå lagt til “passiv fra” dato for medlem i RJJK web som kan settes og oppheves.

--
Uwe Kubosch
uwe@kubosch.no

**Comment by saxofonia** [comment]
Bra!

Det er dessverre ikke samsvar mellom mobilnummer til foresatte. Gjorde en
endring i både dette, og mailadressen (som hadde en liten feil).
Mailadressen ble rettet opp hos nkf, men ikke mobilnummeret.
[image: Innebygd bilde 1]



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766


4. september 2017 kl. 10:40 skrev Uwe Kubosch <notifications@github.com>:

> Woohoo!
>
> Jeg har nå lagt til “passiv fra” dato for medlem i RJJK web som kan settes
> og oppheves.
>
> --
> Uwe Kubosch
> uwe@kubosch.no
>
>
>

**Comment by donv** [comment]
Da har jeg oppdatert overføringen til NKF fra vårt register litt.  Blir mobilnummer riktig nå?

--
Uwe Kubosch
uwe@kubosch.no

**Comment by saxofonia** [comment]
Hei!

Jeg gjorde en endring på foresattes mobil, på et medlem, og ventet en tid.
Jeg ser under fanen NKF at det blir overført, men blir ikke plassert på
Foresatte 2's telefon under fanen "Detaljer".

[image: Innebygd bilde 1]

[image: Innebygd bilde 2]



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766


7. januar 2018 kl. 10:32 skrev Uwe Kubosch <notifications@github.com>:

> Da har jeg oppdatert overføringen til NKF fra vårt register litt. Blir
> mobilnummer riktig nå?
>
> --
> Uwe Kubosch
> uwe@kubosch.no
>
>
>
