### ISSUE TITLE
Link til Epostlister feiler

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#171]
Jeg leter egentlig etter plass for masseutsendelse av sms, men kommer heller ikke inn på plass for masseutsendelse av sms.
<img width="720" alt="Skjermbilde 2021-03-15 kl  19 11 57" src="https://user-images.githubusercontent.com/28863697/111206521-c3364800-85c8-11eb-8ff4-0d89027e4def.png">

**Comment by donv** [comment]
Ser på denne nå.

**Comment by donv** [comment]
Langtidsplan er å gå inn på "Drilldown", finne de medlemmene man ønsker å sende til, og så velge "Send SMS" eller "Send e-post".

**Comment by saxofonia** [comment]
Og korttidsplanen er...?


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: ***@***.***
Web: http://www.jujutsu.no



lør. 8. mai 2021 kl. 22:35 skrev Uwe Kubosch ***@***.***>:
