### ISSUE TITLE
Evig scrolling

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#173]
Fra @Vegandi :

https://user-images.githubusercontent.com/57275/117547397-adc12580-b02f-11eb-8ecf-c03b3b126db5.mp4

**Comment by donv** [comment]
Prøver å fikse denne, men har ikke klart å fremtvinge den hos meg enda.

@Vegandi Har du en måte du får ristingen på hver gang?

**Comment by donv** [comment]
Da skal det være i orden.  Ta gjerne og test det @Vegandi .

**Comment by Vegandi** [comment]
Ok, will do. 😉

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

lør. 8. mai 2021, 21:08 skrev Uwe Kubosch ***@***.***>:

**Comment by Vegandi** [comment]
Jeg har samme problemet enda, men ikke i Chrome (bruker vanligvis Edge).

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


lør. 8. mai 2021 kl. 21:08 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Kan du sjekke en gang til nå?


--
Uwe Kubosch
***@***.***

**Comment by Vegandi** [comment]
Nå funker det! :-)

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


lør. 8. mai 2021 kl. 21:42 skrev Uwe Kubosch ***@***.***>:

> Kan du sjekke en gang til nå?
>
>
> --
> Uwe Kubosch
> ***@***.***
>
>
>
