### ISSUE TITLE
SMS-meldinger fra "drill down" blir ikke sendt

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#177]
Jeg fikk ikke sendt sms-meldinger via "drill down". Det indikeres at det ble sendt melding, men jeg mottok ingen. Både jeg og Atle prøvde fra hver vår plass, mot hvert vårt medlem.

Det ble på styremøte bestemt at vi skal sende sms til medlemmer med viktige beskjeder. Da må dette virke. Det ble også snakket om å kunne velge foreldre/barn som mottaker før utsendelse.

Tilgang til å sende sms bør være via Administrasjon-Medlemmer-Telefonliste (https://www.jujutsu.no/members/telephone_list). I dag finnes kun medlemmets mobilnummer her. Det bør også fremkomme foreldres nummer som et alternativ/valg.

**Comment by donv** [comment]
@AtleTollefsen tok kontakt med meg halv fire i dag, og feilen ble rettet kl 18, altså en halvtime før du la inn denne saken.

Minner om at dette er en helt ny funksjon som ingen har testet enda.  Test den før dere vil bruke den.

Nye funksjoner, som hvordan telefonnummer skal velges, må utvikles, og det må gjøres i samarbeid med de som skal bruke det.  Hvis dere ikke har involvert dere i utviklingen, kan dere ikke gå ut fra at funksjonen finnes.  Det holder ikke å si at noe burde være på et vis, man må involvere seg i arbeidet.

**Comment by saxofonia** [comment]
OK. Nå satt vi å pratet om dette på styremøtet i går, og vi ble enige om at
vi skulle benytte sms til kommunikasjon av viktige beskjeder, og at det
webben skulle benyttes til dette. Det skulle utvikles funksjoner for å få
dette til. At jeg skrev dette her var som en tjeneste til utviklingsmiljøet
slik at vi fikk med oss dette.

Jeg har ikke fått beskjed om å teste noen sms-funksjon så vidt jeg kan
erindre. Om Atle har fått beskjed om at feilen er rettet, har han glemt å
meddele dette til meg. Vi var enige om at jeg skulle lage en feilmelding i
Github, men rakk ikke det med en gang.

Dersom det er plagsomt at vi ønsker oss funksjoner i systemet kan vi
sikkert droppe det, og fokusere på andre systemer. Det er helt frivillig,
sånn jeg ser det, å utvikle denne webben, og jeg har tidligere uttrykt
bekymring for at det bare er én person som kan utvikling av dette. Jeg er
klar over at kildekoden ligger på Github, men tviler på at jeg er kapabel
til å finne ut av det om det skulle behøves. Det bør rekrutteres en eller
flere som kan lære utvikling av systemet, men altså ikke meg.


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: ***@***.***
Web: http://www.jujutsu.no



tor. 20. mai 2021 kl. 20:35 skrev Uwe Kubosch ***@***.***>:
