### ISSUE TITLE
Kan vi få lenke til forsida fra den store logoen på høyre side? 

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#181]
Jeg klikker ALLTID på den store fine logoen til høyre, er det ikke logisk at den fører til forsida?

**Comment by donv** [comment]
Bedre nå?

**Comment by Vegandi** [comment]
Ja, det ser ut til å funke fint. Tusen takk! 👍🏻 

Og så blir jeg så glad av at den logoen hopper inn i midten av sida når en gjør vinduet mindre, det er så stilig!

**Comment by donv** [comment]
> Og så blir jeg så glad av at den logoen hopper inn i midten av sida når en gjør vinduet mindre, det er så stilig!

La inn slik at logoen hopper til banneret når du ruller med høyre kolonne.  Ser det greit ut?  @Vegandi

**Comment by Vegandi** [comment]
Ja, enda stiligere. Nå blei jeg enda litt gladere. :-)
