### ISSUE TITLE
Treig lasting av nettsida i dag

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#187]
Jeg har vært inne på nettsida og smårydda litt i dag, og den er veldig treig. Bruker Edge. Chrome er også treig, men ikke like treig som Edge. Er det noe vedlikehold eller noe sånt som går og tikker i bakgrunnen?

**Comment by Vegandi** [comment]
Nettsida nå rask som et lyn igjen!

**Comment by donv** [comment]
Da sier vi det er greit for denne gang :)

**Comment by Vegandi** [comment]
👍🏻😊

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

tir. 27. jul. 2021, 12:39 skrev Uwe Kubosch ***@***.***>:
