### ISSUE TITLE
Ny side med hilseseremoni

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#199]
Med flere instruktører og -spirer på matta, kunne det vært greit å ha hilseritualene tigjengelige på web. Veit at Tuan blant annet ville ha hjelp til å huske hva man skal si når. :-)

**Comment by donv** [comment]
Lagt inn på https://www.jujutsu.no/info/25 og lagt inn som en pensumartikkel for gult belte.

**Comment by Vegandi** [comment]
Supert! 👍🏻

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

ons. 15. sep. 2021, 20:42 skrev Uwe Kubosch ***@***.***>:
