### ISSUE TITLE
"Bekreft"-knapp ved innmelding virker ikke? 

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#203]
Jeg registrerte ett nytt medlem forrige uke, på min telefon, i dojoen (garderoben for å være helt presis). Da vi kom til siste side og skulle trykke på siste knappen, så var den uten respons, virka det som. Jeg trykka flere ganger, for det var litt vanskelig å se om den responderte. Etter treninga så jeg at hun var registrert (Weronika Bukat). Så på torsdag hadde vi ei ny tigerjente som skulle prøve, og jeg fikk henne til å gjøre det på egen telefon. Fikk henne på nettet, og hun trykka seg gjennom. Men hun opplevde også at knappen ikke så ut til å funke, og etter treninga (jeg fikk ikke sjekka før etter trening) var hun ikke registrert. Er det pga treigt nett, eller er det noe her?

**Comment by donv** [comment]
Rettet endel feil i innmeldngen i dag.  Nå skal det være i orden.

**Comment by Vegandi** [comment]
Så bra! Akkurat dette er veldig viktig at går glatt, for det er jo
førsteinntrykket vårt. Får man en bekreftelse også, "Takk, registreringa di
er mottatt" eller noe sånt?

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


fre. 19. nov. 2021 kl. 01:00 skrev Uwe Kubosch ***@***.***>:
