### ISSUE TITLE
Nullstille påmeldingsknapper

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#204]
Det hender (ganske ofte) at jeg pølsefingrer til oppmøteregistrering og trykker "Trente" på en tiger eller to som ikke har vært der. Men når jeg først har vært borti den knappen, så må jeg velge en fraværsgrunn. Kunne vi ikke bare få gå tilbake til den grå startknappen?

**Comment by donv** [comment]
For fremtidige treninger går knappen tilbake til den grå "Kommer?" knappen.  For pågående eller tidligere treninger går den til "Forhindret" som er den uspesifiserte "trente ikke" tilstanden.  Tanken er at treningen pågår eller er ferdig, så du vet jo om personen var tilstede eller ikke.  Du trenger ikke velge mer spesifik grunn hvis du ikke vil.

Gir det mening?  Vil du heller ha den grå "Trente?" eller "Trener?" knappen?

**Comment by Vegandi** [comment]
Makes sense! 👍

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


fre. 19. nov. 2021 kl. 01:09 skrev Uwe Kubosch ***@***.***>:
