### ISSUE TITLE
Hjelpetekst eller send-knapp på arrangement

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#205]
Når man skal sende ut melding til arrangementsdeltagere, så ville det vært fint med enten en "Lagre"-knapp, eller en "Send"-knapp når man er ferdig med å redigere meldinga. For oss vanlige dødelige er det ikke særlig logisk at "Klar til utsending" betyr at meldinga kommer til å bli sendt neste gang serveren får et rykk. Hjelpetekst burde være et minimum.

**Comment by donv** [comment]
Denne fikset vi sammen.

**Comment by Vegandi** [comment]
Jepp! Vi var flinke! 🥰

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

man. 22. nov. 2021, 19:23 skrev Uwe Kubosch ***@***.***>:
