### ISSUE TITLE
Dobbelt opp av fritrening

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#206]
Blei visst litt mye Møllers tran på de fritreningene. Eller er det bare jeg som får tilbud om ekstra fritrening? :-) 

![IMG_20211027_092210603](https://user-images.githubusercontent.com/73274461/139023039-c0a9ab48-e7c9-4a32-a207-9e2b7d4c3335.jpg)

**Comment by donv** [comment]
Bedre nå?

**Comment by Vegandi** [comment]
Denne har du også fiksa før, og er fortsatt i orden. :-)
