### ISSUE TITLE
Graderingskrøll

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#207]
Tenkte å legge til kandidater til gradering på Tiger (egentlig Morten sin jobb, så jeg skal delegere), men da jeg la til Erik (som skal ha blått belte med hvit stripe), så sto han plutselig oppført med 5. kyu?! Jeg kan endre tilbake, men det er jo litt tungvint, for da må jeg jo huske hvilken grad de skal ha... 

Så prøvde jeg å legge til nederst, de som står nederst og skal ha lavest grad. Der endra det seg IKKE, men der kom det opp en advarsel om at det er aldersgrense 14 år på 9. mon. Det er det jo ikke, så her er det også noe krøll.

**Comment by donv** [comment]
Denne er i orden nå?

**Comment by Vegandi** [comment]
Denne er også i orden. Tusen takk!
