### ISSUE TITLE
Krøll med mon-gradene i pensumsoversikt

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#208]
Etter at jeg la inn pensum på 10. og 9. mon, har de plutselig lagt seg nederst i lista over grader, og har blitt oppført med 15-årsgrense. Trur ikke jeg har endra noe på posisjon underveis, så dette er nok en bug. 

https://www.jujutsu.no/curriculum_groups/4

**Comment by donv** [comment]
Er dette greit nå?

**Comment by Vegandi** [comment]
Ja, det har vært i orden siden helga. :-) Det jeg ikke har kontroll på er om aldersgrensene er rette, men kan sikkert du se over?

**Comment by donv** [comment]
Jevnt over er det 10-års grense for å trene på Tiger og 6 måneder mellom gradene, så det hopper ett år oppover for hver grad.

**Comment by Vegandi** [comment]
> Jevnt over er det 10-års grense for å trene på Tiger og 6 måneder mellom gradene, så det hopper ett år oppover for hver grad.

Det er akkurat den informasjonen du har i hodet og som jeg må finne på webben. Men jeg tar innpå deg!
