### ISSUE TITLE
Enkelte søsken blir registrert som "folk".

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#209]
Gabriel Dalloul står oppført som både "folk" og medlem (aktivert fra prøvemedlem). "Folk"-oppføringen er registrert med 9 Tigertreninger, mens medlemmet er registrert med 2 Tigertreninger. Kan disse to "slås sammen" med nevnte funksjon uten at det blir krøll? Hvem er tyngst? "Folk" eller "Medlem"?

Jeg antar at årsaken til at dette skjer er at noen fremmedspråklige foreldre som registrerer søsken ikke forstår at det er foresatte de skal registrere. Kanskje de ikke vet hva ordet "foresatte" betyr? Hva kan vi gjøre for at dette ikke skjer? Det er ikke første gang. Mir ble også registrert som "foresatt" til sin bror Las her om dagen...

**Comment by donv** [comment]
Funksjonen for å slå sammen to brukere er blitt så bra at du kan bruke den.  Det er nok lurt om jeg er med første gangen for å forklare litt og få tips om forbedringer.  Du finner den i nedtrekksmenyen i brukerbildet.

Jeg vet ikke hvordan vi kan gjøre innmeldingen lettere.  "Foresatt" er det riktige ordet, men jeg er med på å endre det hvis vi finner noe bedre.

**Comment by Vegandi** [comment]
Vi må kunne bruke uttrykket "foresatt", vi får heller innse at vi må rydde litt.

**Comment by donv** [comment]
"Forelder / Foresatt" i overskrift og prosa?

![Screen Shot 2021-11-19 at 13 35 05](https://user-images.githubusercontent.com/57275/142623823-5a01ea82-a95b-41df-8796-324b1fdc16ca.png)

**Comment by Vegandi** [comment]
"...trenger vi kontaktopplysninger til en forelder eller foresatt". 

<3 Arne, 6 år. <3

**Comment by saxofonia** [comment]
Hei!

Greit nok for meg, men da er nok heller den generelle språkkompetansen et
problem. Utfordringen er om vi ønsker å tilrettelegge for engelsk i tillegg?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



fre. 19. nov. 2021 kl. 13:40 skrev Ellen Skjold Kvåle <
***@***.***>:

**Comment by donv** [comment]
Jeg kan legge inn engelske tekster hvis ønskelig.  Kanskje verdt å ta opp på styremøtet som policy om man må forstå norsk for å trene hos oss?

**Comment by saxofonia** [comment]
Kan du ta det opp som sak?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



lør. 20. nov. 2021 kl. 03:00 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Hei!

Ja, tar det gjerne opp som sak.  Går det som “eventuelt” på møtet?


--
Uwe Kubosch
***@***.***

**Comment by donv** [comment]
OK


--
Uwe Kubosch
***@***.***

**Comment by donv** [comment]
Stenger denne saken, og så følger vi det opp som styresak.
