### ISSUE TITLE
Mulighet til å konvertere "folk" til "Medlem"

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#210]
Noen ganger velger en foresatt å melde seg inn i klubben for å trene, f.eks. på TrimForeldre, eller rett og slett delta som styremedlem. Da hadde det vært enkelt å kunne konvertere dem enkelt fra "folk" til "medlem".

**Comment by donv** [comment]
Legge til et valg på brukersiden oppe til høyre med "Meld inn" ?

Kanskje en knapp med "Meld deg inn" hvis brukeren er innlogget?

**Comment by donv** [comment]
Da har jeg lagt til et valg i nedtrekksmenyen i brukerbildet med "Meld inn".

Ser det greit ut?  Du må legge inn innmeldingsdato, resten er valgfritt.

**Comment by donv** [comment]
@saxofonia har du fått sett på dette?
