### ISSUE TITLE
Det er ikke mulig å registrere nytt prøvemedlem når det allerede finnes en "bruker" på vedkommende

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#211]
Det er ikke mulig å registrere nytt prøvemedlem når det allerede finnes en "bruker" på vedkommende. Jeg klikker på "Meld inn" gjentagende, men det hender ingenting.

**Comment by saxofonia** [comment]
Et eksempel er Joakim Øien Iversen.

**Comment by donv** [comment]
Skal se på det i dag.

**Comment by donv** [comment]
Har funnet problemet.

**Comment by donv** [comment]
Hullo!

Da har jeg fikset masse!  Nå skal registrering av eksiterende bruker være greit.
