### ISSUE TITLE
Medlemsansvarlig blir spammet av mailer for påmelding av nytt medlem

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#213]
Det tyter inn mailer om at Jim Aagren har meldt seg inn hele tiden. Dette bør stoppes.

I tillegg får man alltid 2 mailer for hver nye påmeldte.

**Comment by donv** [comment]
Ser på det nå.

**Comment by donv** [comment]
Har det stoppet nå?

Slettet du Jim Aagren sin innmelding?

**Comment by saxofonia** [comment]
Hei!

Stoppet, ja. Siste mail i dag kl. 0900. Jeg har ikke slettet noe.


SRR

søn. 21. nov. 2021, 13:57 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Har fjernet de doble meldingene.
