### ISSUE TITLE
Legge til kommentar og rekkefølge på teknikkvideoene for å dokumentere grunnform og varianter

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#215]
Dette er nå lagt til.

**Comment by donv** [comment]
@Vegandi Ser greit ut?

**Comment by Vegandi** [comment]
Det ser veldig bra ut, fint at vi kan legge til kommentarer under videoene.
Men akkurat de videoene som ligger på 3. kyu nå, disse to variantene til
shodan+, de synes jeg faktisk ikke bør ligge på 3.kyu i det hele tatt, før
vi har den egentlige teknikken der. Det kastet er krøkkete nok å få til i
standardutgaven, det siste en trenger er en video av noe som ikke er den
teknikken, men som ligner.

Alt godt,

Ellen

--
Ellen Skjold Kvåle
Solvegen 18C
2005 RÆLINGEN
Telefon: +47 920 95 703 <https://aidbox.org/ct/?i=525466000001511&t=1>


tir. 23. nov. 2021 kl. 09:19 skrev Uwe Kubosch ***@***.***>:
