### ISSUE TITLE
Instruktørsider

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#227]
Lage en mal for instruktørsider.

**Comment by Vegandi** [comment]
Kommite skrives slik: komite eller komité

Helsing redaktøra.

**Comment by Vegandi** [comment]
Fin mal! Veldig fint å kunne se hvem som er instruktører.

**Comment by donv** [comment]
Har rettet skrivefeilen.  Si ifra hvios det andre ting som bør endres.
