### ISSUE TITLE
Oppgavekort på framsida

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#228]
Oppgaver kommer opp som kort på framsida, feks godkjenne grader, sette opp gradering osb.

**Comment by donv** [comment]
Har lagt til kort for godkjenning av grader.  Tar andre kort ved senere anledning.  Meld ifra når det trengs et kort.

**Comment by Vegandi** [comment]
Bra jobba! Jeg har ikke fått sett åssen korta ser ut, men regner med at det
blei veldig bra.

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

man. 20. des. 2021, 11:40 skrev Uwe Kubosch ***@***.***>:
