### ISSUE TITLE
Alle medlemmer er blitt instruktører

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#230]
Nå kommer en inn på instruktørbeskrivelse uansett hvilket medlem man klikker på fra medlemslista...
![Screenshot_20211215-140336](https://user-images.githubusercontent.com/73274461/146199473-bff45e2e-79c1-42a2-8c6b-fb9df6e4dc4a.png)
![Screenshot_20211215-134923](https://user-images.githubusercontent.com/73274461/146199477-6c3fa2d3-a358-42ec-9fe0-be1f171a76c7.png)

**Comment by donv** [comment]
Fikset.  Bedre nå?
