### ISSUE TITLE
Mange epostmeldinger på samme sak

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#254]
Jeg får 6 (!) eposter på samme sak, Trolig sendes en epost til alle for alle deltagere? Så hvis det var 7 deltagere ville jeg fått 7 (!) eposter?

![image](https://user-images.githubusercontent.com/28863697/157189734-ddd1aa2c-f197-45f0-b7d9-5461bb2ae303.png)

**Comment by donv** [comment]
Hmm, skal se på det.  Det kan være i forbindelse med litt omskriving av meldingsutsending.

**Comment by donv** [comment]
Jeg fikk 8 like meldinger i dag, jeg også.  Er opptatt på jobb, og så treing i kveld, men skal se på det så fort jeg kan.

**Comment by Vegandi** [comment]
Fikk nettopp melding fra Anja Sørensen om at hun hadde fått 16 e-poster om at det ikke er trening for panda pga årsmøtet. Jeg sjekka innboksen min, og jeg fikk bare en...

**Comment by saxofonia** [comment]
Jeg fikk 4, men fikk derimot 7 meldinger om trening i kveld...



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



tir. 15. mar. 2022 kl. 15:43 skrev Ellen Skjold Kvåle <
***@***.***>:

**Comment by donv** [comment]
Da tror jeg at jeg har funnet og rettet feilen!  Legger det ut nå, så får vi se hvordan det går i produksjon.

**Comment by Vegandi** [comment]
Nydelig! Bra jobba!

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

søn. 20. mar. 2022, 01:51 skrev Uwe Kubosch ***@***.***>:
