### ISSUE TITLE
Ov

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#264]
![signal-2022-03-21-075018_002](https://user-images.githubusercontent.com/73274461/159256640-45589f18-32e2-4cf8-af8e-4b814cdb479a.png)
![signal-2022-03-21-075018_001](https://user-images.githubusercontent.com/73274461/159256667-f7a4db29-3d4c-4386-9622-ffa3df5d8d30.png)

Hvorfor står det forskjellig minimumsantall treninger på graderingssida og her, og det samme med oppmøtet hans? Finnes det ei oversikt over antallet treninger som er påkrevd til nytt belte? Kan vi eventuelt få det?

**Comment by donv** [comment]
Har lagt inn visning av standard antall treninger i oversikten over grader nå.

For en enkelt utøver prøvde jeg å lage en utregning som tar høyde for innmeldingsdato og dato for forrige gradering og dato for neste gradering.  Det kan gi litt andre tall.  Jeg skal se over igjen og sørge for at det gir mening.

**Comment by donv** [comment]
Fant en forskjell i avrunding for minste antall treninger.  Nå skal det være likt.
