### ISSUE TITLE
Bakgrunnsbilde feiler på offentlig forside

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#266]
Det øverste bakgrunnsbildet på den offentlige forsida feiler, en ser et uklart pdf-ikon i stedet. Kan være et problem med bilder, for inne på sida for Priser og innmelding er det også et bilde som feiler. Lager ny sak på det.

**Comment by donv** [comment]
Bra nå?

**Comment by Vegandi** [comment]
Jepp! Bra jobba!

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

ons. 23. mar. 2022, 13:06 skrev Uwe Kubosch ***@***.***>:
