### ISSUE TITLE
Bilde feiler

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#267]
Inne på sida "Priser og innmelding" feiler bildet. 

Rettelse: det ser ut til at bilder feiler generelt i dag.

Er du ikke glad for at du hver dag våkner til meldinger fra meg om ting som må fikses? :-/

**Comment by donv** [comment]
Fikset.

**Comment by Vegandi** [comment]
Så det! Bra jobba!

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

ons. 23. mar. 2022, 12:58 skrev Uwe Kubosch ***@***.***>:
