### ISSUE TITLE
Sletting av treninger ser ikke ut til å gi noen endringer

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#274]
Har fått mas fra systemet om å legge inn første og siste treningsdag for Panda, og i den forbindelse prøvde jeg å slette treninga i uke 40, som er 6. oktober. Jeg får tilbakemelding om at den er sletta, men den står der like fullt. Har sett det samme i dette semesteret, har prøvd å fjerne påskeferien og himmelspretten, men de står der likevel. Jeg kan for eksempel melde meg på som instruktør for Panda neste uke.

**Comment by donv** [comment]
Ser på det nå.

**Comment by donv** [comment]
Vi snakker om denne, ikke sant?

https://www.jujutsu.no/group_semesters/106/edit#plan_tab

**Comment by Vegandi** [comment]
> Vi snakker om denne, ikke sant?
> 
> https://www.jujutsu.no/group_semesters/106/edit#plan_tab

Jepp.

**Comment by donv** [comment]
Ser det greit ut nå?

**Comment by Vegandi** [comment]
Ser veldig bra ut! Tusen takk!

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

ons. 13. apr. 2022, 07:06 skrev Uwe Kubosch ***@***.***>:
