### ISSUE TITLE
Menylinjen følger ikke faktisk oppløsning, så deler av menyen blir borte ved lavere oppløsning.

### ISSUE THREAD

**Issue by saxofonia** [Romerike-Jujutsu-Klubb/rjjk_web#276]
![image](https://user-images.githubusercontent.com/28863697/161695805-b62e4579-bc09-4d3d-b1dc-0e3b5dba6ee1.png)

![image](https://user-images.githubusercontent.com/28863697/161695890-4a46efc1-d351-49c4-9f41-a2b6bb651d47.png)

![image](https://user-images.githubusercontent.com/28863697/161695957-ab3eeb37-876b-4951-952d-857e61834672.png)

**Comment by donv** [comment]
Fjernet "Ny markedsføringsgruppe fra forsiden.  Da ble det bedre plass.

**Comment by saxofonia** [comment]
Funket ikke, da!



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: ***@***.***
Web: http://resvero.com/

Mobil: +47 97534766



tir. 5. apr. 2022 kl. 16:36 skrev Uwe Kubosch ***@***.***>:

**Comment by donv** [comment]
Hva var det som ikke funket?
