### ISSUE TITLE
Innlogging via SMS

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#28]
Finne en gratis løsning.

**Comment by donv** [comment]
@saxofonia Da har jeg lagt til innlogging via SMS.  Jeg bruker Datek sin løsning til jeg kan finne en annen gratis løsning.

Kan du teste løsningen og logge inn på telefonen via SMS?

**Comment by saxofonia** [comment]
Hvordan da?

lør. 18. mai 2019, 20:45 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
😀 Jeg håpet det var selvforklarende.  Hvis du logger ut på telefonen og så velger "Medlemssider" fra menyen, så kommer du til en side for innlogging.  Forklaringen der må være god nok til at medlemmer forstår hvordan de kan logge seg på med SMS.  Kan du se på det og gi tips til forbedringer?On May 20, 2019 06:53, saxofonia <notifications@github.com> wrote:Hvordan da?



lør. 18. mai 2019, 20:45 skrev Uwe Kubosch <notifications@github.com>:

**Comment by saxofonia** [comment]
Hehehe. Så ikke det jeg. Bare logget inn som vanlig uten å lese teksten!
:-)

Prøvde nå, og det fungerer som gull!  👍


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: post@jujutsu.no
Web: http://www.jujutsu.no



man. 20. mai 2019 kl. 07:52 skrev Uwe Kubosch <notifications@github.com>:
