### ISSUE TITLE
Kan ikke vise oppmøte

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#280]
![Screenshot_20220413-210456](https://user-images.githubusercontent.com/73274461/163252093-c0921704-fbf7-46b2-a4e4-81a6e8391c80.png)

Kan ikke vise oppmøte.

**Comment by donv** [comment]
Virker vel ok nå?

**Comment by Vegandi** [comment]
Har vært opptatt med påskekrim, men fungerte som normalt i dag tidlig. 👍🏻

Alt godt,

Ellen Skjold Kvåle

Denne meldinga er sendt fra en mobiltelefon.

fre. 15. apr. 2022, 20:09 skrev Uwe Kubosch ***@***.***>:
