### ISSUE TITLE
Får ikke registrert foresatt som komitemedlem 

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#308]
Faren til Leander, Jørn, vil gjerne være med i sosialkomiteen, men jeg får ikke lagt ham til som medlem i lista. Aner meg at det har med hvordan foresatte er lista opp, men veit ikke helt.

**Comment by donv** [comment]
Ja, jeg har satt opp at bare medlemmer kam bli med i komtéer.  Jeg endrer det slik at alle kan bli med.

**Comment by Vegandi** [comment]
Ja, viss vi ser at det blir problemer får vi heller fikse det. Det går kanskje an å låse det til de som er foresatte, eller i alle fall registrerte med navn et sted på webben?

**Comment by Vegandi** [comment]
Superdupert, tusen takk! :-)
