### ISSUE TITLE
Flytte plusstegnet til Web-fane? 

### ISSUE THREAD

**Issue by Vegandi** [Romerike-Jujutsu-Klubb/rjjk_web#313]
I løpet av siste uka har både Morten og jeg blitt lurt til å trykke på det store synlige plusstegnet i venstremargen når vi skulle lage en nyhet. Resultatet er at vi begge har laga nye informasjonssider, og ikke nyhetssaker. Kanskje det er under web-fana at plusstegnet skal være synlig uten å rulle ned menyen?

**Comment by donv** [comment]
Fjernet plussen på informasjonsmenyen.  Den er fremdeles tilgjengelig under web-menyen.
