### ISSUE TITLE
Ny mer fokusert oppmøteføring for instruktører

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#45]
* Visning som er bedre på telefon/pad
* Færre klikk

**Comment by donv** [comment]
@AtleTollefsen @Atle-Tollefsen Hei!

Jeg har lagt inn et forslag til ny oppmøteføring her:

    https://www.jujutsu.no/oppm%C3%B8te/skjema

Det er nå en tab for `Panda` der du skal kunne føre neste trening raskere.

Jeg tenker å legge til en nedtrekksmenu for å velge andre treninger enn den neste.

Jeg har lagt til en `+ Nytt oppmøte`-knapp der man kan legge til uventede utøvere og instruktører på en trening.

Kan du se på det og gi tilbakemelding?

**Comment by donv** [comment]
@AtleTollefsen @Atle-Tollefsen 

Da har jeg lagt til valg av trening og tenker at denne funksjonen er klar til bruk.

Kan du se på den og gi tilbakemelding?

https://www.jujutsu.no/oppm%C3%B8te/skjema

**Comment by AtleTollefsen** [comment]
Ser meget bra ut. Toppers! Du er flink altså!.......


Med vennlig hilsen

Atle Tollefsen
IT seniorkonsulent

Securitas AS
Postboks 100 Alnabru, 0614 OSLO
Besøksadresse: Bøkkerveien 5, 0579 OSLO

Mobiltelefon: +4741295454    Sentralbord: 02452 eller +47 22 57 73 08
Email: atle.tollefsen@securitas.no

[cid:image001.png@01D56166.A3A18E10]

Vi tilbyr alt av sikkerhet til din bedrift. Les mer på: www.securitas.no
Disclaimer: The contents of this e-mail message (including any attachments hereto) are confidential to and for the use of the recipient to whom it is addressed only. If you receive this transmission in error, please notify the sender of this immediately and delete the message from your system. Any distribution, reproduction or use of this message by someone other than recipient is not authorized and may be unlawful.
P Please consider the environment before printing this e-mail.

[cid:image003.png@01D56166.A3A51080]


Fra: Uwe Kubosch <notifications@github.com>
Sendt: søndag 1. september 2019 02:01
Til: Romerike-Jujutsu-Klubb/rjjk_web <rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen <atle.tollefsen@securitas.no>; Mention <mention@noreply.github.com>
Emne: [External] Re: [Romerike-Jujutsu-Klubb/rjjk_web] Ny mer fokusert oppmøteføring for instruktører (#45)


@AtleTollefsen<https://github.com/AtleTollefsen> @Atle-Tollefsen<https://github.com/Atle-Tollefsen>

Da har jeg lagt til valg av trening og tenker at denne funksjonen er klar til bruk.

Kan du se på den og gi tilbakemelding?

https://www.jujutsu.no/oppm%C3%B8te/skjema
