### ISSUE TITLE
Legge til video på pensumapplikasjon

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#57]

**Comment by donv** [comment]
@AtleTollefsen @Atle-Tollefsen @saxofonia Da har jeg lagt til slik at man kan laste opp video for pensumteknikkene.

**Comment by AtleTollefsen** [comment]
Herlig

Få Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Uwe Kubosch <notifications@github.com>
Sendt: Sunday, September 29, 2019 9:54:35 PM
Til: Romerike-Jujutsu-Klubb/rjjk_web <rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen <atle.tollefsen@securitas.no>; Mention <mention@noreply.github.com>
Emne: [External] Re: [Romerike-Jujutsu-Klubb/rjjk_web] Legge til video på pensumapplikasjon (#57)


@AtleTollefsen<https://github.com/AtleTollefsen> @Atle-Tollefsen<https://github.com/Atle-Tollefsen> @saxofonia<https://github.com/saxofonia> Da har jeg lagt til slik at man kan laste opp video for pensumteknikkene.
