### ISSUE TITLE
Flytte domenet fra Webhuset til DomeneShop

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#65]
@saxofonia @AtleTollefsen @Atle-Tollefsen @Romerike-Jujutsu-Klubb/web 

Vi hadde jo opprinnelig avtalt å vente til våren før vi flytter domenet `jujutsu.no` til DomeneShop, men jeg opplever at oppsettet på Webhuset er et større problem enn jeg tidligere trodde.

Jeg tenker å flytte domenet til Domeneshop nå med en gang for å støtte den gode markedsføringstrenden vi er inne i.

Flyttingen blir nok gratis, og årsavgiften blir omtrent lik som hos Webhuset.

Har dere noen innspill?

**Comment by donv** [comment]
@saxofonia @AtleTollefsen @Atle-Tollefsen 

Da har jeg bestilt flytting fra Webhuset til Domeneshop.  Flyttingen bør være klar på et par virkedager.

**Comment by donv** [comment]
Oppsett av e-post videresending og e-postlister vil ta litt tid.  Sier ifra når det er klart.

**Comment by AtleTollefsen** [comment]
Flott

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Uwe Kubosch <notifications@github.com>
Sendt: Friday, November 1, 2019 8:04:55 AM
Til: Romerike-Jujutsu-Klubb/rjjk_web <rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen <atle.tollefsen@securitas.no>; Mention <mention@noreply.github.com>
Emne: [External] Re: [Romerike-Jujutsu-Klubb/rjjk_web] Flytte domenet fra Webhuset til DomeneShop (#65)


Oppsett av e-post videresending og e-postlister vil ta litt tid. Sier ifra når det er klart.

**Comment by saxofonia** [comment]
Supert!  :-)


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: post@jujutsu.no
Web: http://www.jujutsu.no



fre. 1. nov. 2019 kl. 08:08 skrev Atle Tollefsen <notifications@github.com>:

**Comment by donv** [comment]
Hei!

Da er e-post også flyttet.

**Comment by saxofonia** [comment]
Er lister og videresendinger oppdatert på Domeneshop?

Har du påloggingsinfo du kan dele med oss (meg)?



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



fre. 1. nov. 2019 kl. 12:27 skrev Uwe Kubosch <notifications@github.com>:
