### ISSUE TITLE
Video upload direkte til Cloudinary

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#66]
https://cloudinary.com/documentation/rails_image_and_video_upload
https://cloudinary.com/documentation/upload_widget

Dette for å unngå OutOfMemory feil ved opplasting av større filmer.

**Comment by donv** [comment]
@saxofonia @AtleTollefsen @Atle-Tollefsen Har lagt opp en versjon til utprøving nå.  Vi får prøve å filme litt i morgen og teste opplastingen.

**Comment by Atle-Tollefsen** [comment]
Toppers


Sendt fra min iPhone

27. nov. 2019 kl. 20:01 skrev Uwe Kubosch <notifications@github.com>:

﻿

@saxofonia<https://github.com/saxofonia> @AtleTollefsen<https://github.com/AtleTollefsen> @Atle-Tollefsen<https://github.com/Atle-Tollefsen> Har lagt opp en versjon til utprøving nå. Vi får prøve å filme litt i morgen og teste opplastingen.

**Comment by donv** [comment]
Tenker denne er i orden nå.

**Comment by Atle-Tollefsen** [comment]
Toppers tester

Sendt fra min iPhone

3. des. 2019 kl. 18:08 skrev Uwe Kubosch <notifications@github.com>:

﻿

Tenker denne er i orden nå.
