### ISSUE TITLE
Se hvorfor SRR ikke får opp "Neste trening" for tirsdag (voksne)

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#67]

**Comment by donv** [comment]
Har nå endret slik at medlemmer meldt på flere grupper får vist "Neste trening" for alle gruppene de er medlem av.

**Comment by donv** [comment]
@saxofonia Kan du teste?

**Comment by donv** [comment]
@saxofonia Virker dette bra for deg nå?

**Comment by saxofonia** [comment]
Mener å tro det, men nå er jo neste tre i g i morgen. Men, skulle ikke
treningen deretter vært tirsdag?


SRR

lør. 30. nov. 2019, 15:34 skrev Uwe Kubosch <notifications@github.com>:

**Comment by donv** [comment]
Det jeg viser nå er neste trening for hver av gruppene du er medlem av.  Neste trening for Voksne er i morgen og neste trening for TrimForeldre er på torsdag.  Blir det bra?


--
Uwe Kubosch
uwe@kubosch.no

**Comment by saxofonia** [comment]
Da er det riktig! 🙂 👍

lør. 30. nov. 2019, 16:57 skrev Uwe Kubosch <notifications@github.com>:

> Det jeg viser nå er neste trening for hver av gruppene du er medlem av.
> Neste trening for Voksne er i morgen og neste trening for TrimForeldre er
> på torsdag. Blir det bra?
>
>
> --
> Uwe Kubosch
> uwe@kubosch.no
>
>
>
