### ISSUE TITLE
Sende e-post via SendGrid i stedet for WebHuset

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#69]

**Comment by donv** [comment]
Domeneshop tilbyr ikke sending av e-post fra applikasjoner.

Nå brukes SendGrid til å sende e-post med.  Det betyr at vi kan si opp WebHuset.

@saxofonia @AtleTollefsen @Atle-Tollefsen

**Comment by Atle-Tollefsen** [comment]
Jeg går vel ut i fra at domene ikke er sagt opp, men tjeneste er sagt opp. Og at domene fremdeles lever videre.


Sendt fra min iPhone

6. apr. 2020 kl. 21:05 skrev Uwe Kubosch <notifications@github.com>:

﻿

Domeneshop tilbyr ikke sending av e-post fra applikasjoner.

Nå brukes SendGrid til å sende e-post med. Det betyr at vi kan si opp WebHuset.

@saxofonia<https://github.com/saxofonia> @AtleTollefsen<https://github.com/AtleTollefsen> @Atle-Tollefsen<https://github.com/Atle-Tollefsen>

**Comment by donv** [comment]
Domenet skal leve videre hos Domeneshop.
