### ISSUE TITLE
Utvide oppmøtegrensen fra 15 til 30 minutter

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#80]

**Comment by donv** [comment]
@Atle-Tollefsen @AtleTollefsen Da har jeg fikset endel på oppmøteføringen.  Tror den er blitt bra.  Prøv den på tirsdag/torsdag og gi tilbakemelding.

**Comment by Atle-Tollefsen** [comment]
Nice. Takker.



Fra: Uwe Kubosch <notifications@github.com>
Sendt: lørdag 7. desember 2019 16:11
Til: Romerike-Jujutsu-Klubb/rjjk_web <rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen <Atle@gjemmekontor.no>; Mention <mention@noreply.github.com>
Emne: Re: [Romerike-Jujutsu-Klubb/rjjk_web] Utvide oppmøtegrensen fra 15 til 30 minutter (#80)


@Atle-Tollefsen<https://github.com/Atle-Tollefsen> @AtleTollefsen<https://github.com/AtleTollefsen> Da har jeg fikset endel på oppmøteføringen. Tror den er blitt bra. Prøv den på tirsdag/torsdag og gi tilbakemelding.
