### ISSUE TITLE
Ikke sende oppmøtemeldinger til foreldre

### ISSUE THREAD

**Issue by donv** [Romerike-Jujutsu-Klubb/rjjk_web#90]
```
Hei,
 
Ber om at min mailadresse slettes fra denne listen. Det holder at sønnen min mottar disse mailene.
 
Mvh Berit Hansen (mor til Vetle F. Gulbrandsen)
```

**Comment by donv** [comment]
@saxofonia @AtleTollefsen @Atle-Tollefsen 

Jeg endrer slik at foresatte ikke får e-post for barna sine etter at de har fylt 15 år.

Det betyr at ungdommen selv må følge opp informasjon de får fra oss fra de har fylt 15 år.

**Comment by AtleTollefsen** [comment]
Topp



Atle Tollefsen
Service Delivery Owner
Service Management Office Cluster North


Securitas AS
PB. 100, Alnabru,
0614 OSLO
Norway
Visiting address: Bøkkerveien 5, 0579 OSLO, Norway

Mobile Phone: +4741295454
Switchboard: 02452 or +47 22 57 73 08
Email: atle.tollefsen@securitas.no<mailto:atle.tollefsen@securitas.no>


[cid:image001.png@01D5C6D1.73A22B90]

Disclaimer: The contents of this e-mail message (including any attachments hereto) are confidential to and for the use of the recipient to whom it is addressed only. If you receive this transmission in error, please notify the sender of this immediately and delete the message from your system. Any distribution, reproduction or use of this message by someone other than recipient is not authorized and may be unlawful.
P Please consider the environment before printing this e-mail.




Fra: Uwe Kubosch <notifications@github.com>
Sendt: onsdag 22. januar 2020 09:51
Til: Romerike-Jujutsu-Klubb/rjjk_web <rjjk_web@noreply.github.com>
Kopi: Atle Tollefsen <atle.tollefsen@securitas.no>; Mention <mention@noreply.github.com>
Emne: [External] Re: [Romerike-Jujutsu-Klubb/rjjk_web] Ikke sende oppmøtemeldinger til foreldre (#90)


@saxofonia<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsaxofonia&data=02%7C01%7Catle.tollefsen%40securitas.no%7C60bbe6a58fbd456abd2208d79f183229%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637152798576538797&sdata=Ww237YnJj7cNJYOj5iGBc%2Fujwp%2FxoAFyBhEhkD6Wdo8%3D&reserved=0> @AtleTollefsen<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAtleTollefsen&data=02%7C01%7Catle.tollefsen%40securitas.no%7C60bbe6a58fbd456abd2208d79f183229%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637152798576548790&sdata=%2FoGIzmW3sdiHZAZ855robdBVrHkOu2mJoUKyXpy0ghc%3D&reserved=0> @Atle-Tollefsen<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAtle-Tollefsen&data=02%7C01%7Catle.tollefsen%40securitas.no%7C60bbe6a58fbd456abd2208d79f183229%7Cfb0af7d18a8348bc8d2dcd92034c79d4%7C0%7C0%7C637152798576548790&sdata=8u4nHYbab%2F3JxgPPMynUP9cHKaBICcvre6rIjVT45w8%3D&reserved=0>

Jeg endrer slik at foresatte ikke får e-post for barna sine etter at de har fylt 15 år.

Det betyr at ungdommen selv må følge opp informasjon de får fra oss fra de har fylt 15 år.

**Comment by donv** [comment]
Dette kan overstyres ved å sette "Kontakt" for medlemmet.

**Comment by saxofonia** [comment]
Hei!

Problemet her er at jeg ikke kan finne medlemmet. Barnet altså!



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



ons. 22. jan. 2020 kl. 12:14 skrev Uwe Kubosch <notifications@github.com>:

**Comment by saxofonia** [comment]
OK, men da må det sikres at foreldre får forvarsel om dette før barnet
fyller 15 år, slik at de kan registrere en ny mailadresse.



Med vennlig hilsen
*Svein Robert Rolijordet*

Mail: srr@resvero.com
Web: http://resvero.com/

Mobil: +47 97534766



ons. 22. jan. 2020 kl. 10:35 skrev Atle Tollefsen <notifications@github.com

**Comment by donv** [comment]
Ja, jeg tenkte på dette.  Kan hende vi må sende en e-post om at nå er det bare medlemmet selv som får meldingene.

Uansett så brukes “kontakt e-post”, dvs. : 

  * E-post til "Kontakt" hvis den er registrert.
  * E-post til medlemmet hvis den er registrert.
  * E-post til "Foresatt 1" hvis registrert
  * E-post til "Foresatt 2" hvis registrert
  * E-post til "Betaler" hvis registrert

Forskjellen mellom før og etter fylte 15 år er at for de yngre sender vi til alle disse adressene mens for de eldre sender vi bare til den første adressen vi finner.

Høres det greit ut?  Trenger vi å informere foresatte om dette?

**Comment by saxofonia** [comment]
Man kan vel aldri informere for mye, bare det er forståelig?  :-)


Med vennlig hilsen
Svein Robert Rolijordet

*Romerike Jujutsu Klubb*
*Leder*

Mail: post@jujutsu.no
Web: http://www.jujutsu.no



tor. 23. jan. 2020 kl. 11:04 skrev Uwe Kubosch <notifications@github.com>:
